import { Project } from './types';
import { uid } from './projectUtils';

export const seedProjects: Project[] = [
  // 기존 프로젝트들
  {
    id: uid(),
    pjtNo: "PJT-25037",
    name: "Busan Dryer Retrofit",
    country: "Korea",
    city: "Busan",
    status: "진행 중",
    pm: "K. Lee",
    salesManagers: ["J. Kim"],
    designManagers: ["S. Park", "B. Lee"],
    controlManagers: ["M. Choi"],
    productionManagers: ["H. Jung", "K. Yoon"],
    progress: 70,
    startDate: "2025-01-01",
    endDate: "2025-06-30",
    lat: 35.1796,
    lng: 129.0756,
    address: "부산광역시",
    note: "코안다 노즐 테스트 라인 포함",
    budget: 50000000,
    actualCost: 35000000,
    costHistory: [
      {
        id: uid(),
        date: "2025-01-01",
        budget: 50000000,
        actualCost: 30000000,
        costRatio: 60.0,
        note: "초기 예산 설정",
        manager: "K. Lee",
        changeReason: "예산 설정"
      },
      {
        id: uid(),
        date: "2025-03-15",
        budget: 50000000,
        actualCost: 35000000,
        costRatio: 70.0,
        note: "코안다 노즐 교체로 인한 비용 증가",
        manager: "K. Yoon",
        changeReason: "실제 비용 증가"
      }
    ],
    equipmentHistory: [
      {
        id: uid(),
        date: "2025-01-15",
        part: "기구",
        content: "코안다 노즐 마모로 인한 성능 저하",
        action: "새로운 노즐로 교체",
        manager: "K. Yoon"
      },
      {
        id: uid(),
        date: "2025-02-20",
        part: "제어",
        content: "테스트 라인 속도 조정 필요",
        action: "모터 속도 조정 및 테스트",
        manager: "H. Jung"
      }
    ],
  },
  {
    id: uid(),
    pjtNo: "PJT-25038",
    name: "Seoul Coating System",
    country: "Korea",
    city: "Seoul",
    status: "완료",
    pm: "J. Park",
    salesManagers: ["S. Kim"],
    designManagers: ["B. Choi"],
    controlManagers: ["M. Lee"],
    productionManagers: ["H. Kim"],
    progress: 100,
    startDate: "2024-06-01",
    endDate: "2024-12-31",
    lat: 37.5665,
    lng: 126.9780,
    address: "서울특별시",
    note: "자동 코팅 시스템 설치 완료",
    budget: 35000000,
    actualCost: 32000000,
    costHistory: [
      {
        id: uid(),
        date: "2024-06-01",
        budget: 35000000,
        actualCost: 0,
        costRatio: 0.0,
        note: "프로젝트 시작",
        manager: "J. Park",
        changeReason: "예산 설정"
      },
      {
        id: uid(),
        date: "2024-12-31",
        budget: 35000000,
        actualCost: 32000000,
        costRatio: 91.4,
        note: "프로젝트 완료",
        manager: "J. Park",
        changeReason: "실제 비용"
      }
    ],
    equipmentHistory: [],
  },
  {
    id: uid(),
    pjtNo: "PJT-26012",
    name: "Nagoya Web Handling Study",
    country: "Japan",
    city: "Nagoya",
    status: "계획",
    pm: "M. Ito",
    salesManagers: ["T. Tanaka"],
    designManagers: ["Y. Suzuki", "H. Nakamura"],
    controlManagers: ["K. Watanabe"],
    productionManagers: ["A. Yamamoto"],
    progress: 0,
    startDate: "2025-07-01",
    endDate: "2025-12-31",
    lat: 35.1815,
    lng: 136.9066,
    address: "Aichi, Nagoya",
    note: "양면 코팅 라인 안정화",
    budget: 30000000,
    actualCost: 0,
    costHistory: [
      {
        id: uid(),
        date: "2025-07-01",
        budget: 30000000,
        actualCost: 0,
        costRatio: 0.0,
        note: "프로젝트 시작",
        manager: "M. Ito",
        changeReason: "예산 설정"
      }
    ],
    equipmentHistory: [
      {
        id: uid(),
        date: "2025-06-10",
        part: "기구",
        content: "양면 코팅 시스템 코팅 두께 불균일 문제",
        action: "노즐 압력 조정 및 캘리브레이션",
        manager: "Y. Suzuki"
      }
    ],
  },
  {
    id: uid(),
    pjtNo: "PJT-26013",
    name: "Tokyo Automation Upgrade",
    country: "Japan",
    city: "Tokyo",
    status: "진행 중",
    pm: "H. Sato",
    salesManagers: ["K. Yamamoto"],
    designManagers: ["T. Suzuki"],
    controlManagers: ["Y. Tanaka"],
    productionManagers: ["M. Watanabe"],
    progress: 45,
    startDate: "2025-02-01",
    endDate: "2025-11-30",
    lat: 35.6762,
    lng: 139.6503,
    address: "Tokyo",
    note: "자동화 시스템 업그레이드",
    budget: 45000000,
    actualCost: 20000000,
    costHistory: [
      {
        id: uid(),
        date: "2025-02-01",
        budget: 45000000,
        actualCost: 0,
        costRatio: 0.0,
        note: "프로젝트 시작",
        manager: "H. Sato",
        changeReason: "예산 설정"
      },
      {
        id: uid(),
        date: "2025-05-15",
        budget: 45000000,
        actualCost: 20000000,
        costRatio: 44.4,
        note: "진행 중",
        manager: "H. Sato",
        changeReason: "실제 비용"
      }
    ],
    equipmentHistory: [],
  },
  {
    id: uid(),
    pjtNo: "PJT-26014",
    name: "Osaka Quality Control",
    country: "Japan",
    city: "Osaka",
    status: "일시 중단",
    pm: "R. Nakamura",
    salesManagers: ["S. Ito"],
    designManagers: ["K. Tanaka"],
    controlManagers: ["H. Suzuki"],
    productionManagers: ["T. Yamamoto"],
    progress: 30,
    startDate: "2025-01-15",
    endDate: "2025-10-31",
    lat: 34.6937,
    lng: 135.5023,
    address: "Osaka",
    note: "품질 관리 시스템 일시 중단",
    budget: 28000000,
    actualCost: 8500000,
    costHistory: [
      {
        id: uid(),
        date: "2025-01-15",
        budget: 28000000,
        actualCost: 0,
        costRatio: 0.0,
        note: "프로젝트 시작",
        manager: "R. Nakamura",
        changeReason: "예산 설정"
      },
      {
        id: uid(),
        date: "2025-04-20",
        budget: 28000000,
        actualCost: 8500000,
        costRatio: 30.4,
        note: "일시 중단",
        manager: "R. Nakamura",
        changeReason: "실제 비용"
      }
    ],
    equipmentHistory: [],
  },
  {
    id: uid(),
    pjtNo: "PJT-25105",
    name: "Phoenix Quotation Roll Upgrade",
    country: "USA",
    city: "Phoenix",
    status: "진행 중(관리필요)",
    pm: "S. Park",
    salesManagers: ["R. Johnson"],
    designManagers: ["L. Smith"],
    controlManagers: ["D. Brown", "E. Taylor"],
    productionManagers: ["C. Davis"],
    progress: 80,
    startDate: "2025-03-01",
    endDate: "2025-08-31",
    lat: 33.4484,
    lng: -112.0740,
    address: "Phoenix, AZ",
    note: "견적 재협상 대기 - 관리 필요",
    budget: 40000000,
    actualCost: 38000000,
    costHistory: [
      {
        id: uid(),
        date: "2025-03-01",
        budget: 40000000,
        actualCost: 30000000,
        costRatio: 75.0,
        note: "초기 예산 설정",
        manager: "S. Park",
        changeReason: "예산 설정"
      },
      {
        id: uid(),
        date: "2025-05-20",
        budget: 40000000,
        actualCost: 38000000,
        costRatio: 95.0,
        note: "원가 상승으로 인한 관리 필요",
        manager: "R. Johnson",
        changeReason: "실제 비용 증가"
      }
    ],
    equipmentHistory: [
      {
        id: uid(),
        date: "2025-04-05",
        part: "제어",
        content: "견적 시스템 원가 상승으로 인한 견적 재검토 필요",
        action: "공급업체와 재협상 진행 중",
        manager: "R. Johnson"
      }
    ],
  },
  // 미국 추가 프로젝트들 (총 10개)
  {
    id: uid(),
    pjtNo: "PJT-25106",
    name: "New York Smart Factory",
    country: "USA",
    city: "New York",
    status: "진행 중",
    pm: "A. Wilson",
    salesManagers: ["M. Davis"],
    designManagers: ["J. Miller"],
    controlManagers: ["P. Anderson"],
    productionManagers: ["L. Thomas"],
    progress: 60,
    startDate: "2025-01-01",
    endDate: "2025-09-30",
    lat: 40.7128,
    lng: -74.0060,
    address: "New York, NY",
    note: "스마트 팩토리 시스템 구축",
    budget: 60000000,
    actualCost: 36000000,
    costHistory: [
      {
        id: uid(),
        date: "2025-01-01",
        budget: 60000000,
        actualCost: 0,
        costRatio: 0.0,
        note: "프로젝트 시작",
        manager: "A. Wilson",
        changeReason: "예산 설정"
      },
      {
        id: uid(),
        date: "2025-05-15",
        budget: 60000000,
        actualCost: 36000000,
        costRatio: 60.0,
        note: "진행 중",
        manager: "A. Wilson",
        changeReason: "실제 비용"
      }
    ],
    equipmentHistory: [],
  },
  {
    id: uid(),
    pjtNo: "PJT-25107",
    name: "Los Angeles IoT Platform",
    country: "USA",
    city: "Los Angeles",
    status: "계획",
    pm: "B. Garcia",
    salesManagers: ["C. Rodriguez"],
    designManagers: ["D. Martinez"],
    controlManagers: ["E. Hernandez"],
    productionManagers: ["F. Lopez"],
    progress: 0,
    startDate: "2025-08-01",
    endDate: "2026-01-31",
    lat: 34.0522,
    lng: -118.2437,
    address: "Los Angeles, CA",
    note: "IoT 플랫폼 개발",
    budget: 35000000,
    actualCost: 0,
    costHistory: [
      {
        id: uid(),
        date: "2025-08-01",
        budget: 35000000,
        actualCost: 0,
        costRatio: 0.0,
        note: "프로젝트 시작",
        manager: "B. Garcia",
        changeReason: "예산 설정"
      }
    ],
    equipmentHistory: [],
  },
  {
    id: uid(),
    pjtNo: "PJT-25108",
    name: "Chicago Robotics System",
    country: "USA",
    city: "Chicago",
    status: "완료",
    pm: "G. Johnson",
    salesManagers: ["H. Williams"],
    designManagers: ["I. Brown"],
    controlManagers: ["J. Jones"],
    productionManagers: ["K. Garcia"],
    progress: 100,
    startDate: "2024-09-01",
    endDate: "2025-02-28",
    lat: 41.8781,
    lng: -87.6298,
    address: "Chicago, IL",
    note: "로봇 시스템 설치 완료",
    budget: 42000000,
    actualCost: 39500000,
    costHistory: [
      {
        id: uid(),
        date: "2024-09-01",
        budget: 42000000,
        actualCost: 0,
        costRatio: 0.0,
        note: "프로젝트 시작",
        manager: "G. Johnson",
        changeReason: "예산 설정"
      },
      {
        id: uid(),
        date: "2025-02-28",
        budget: 42000000,
        actualCost: 39500000,
        costRatio: 94.0,
        note: "프로젝트 완료",
        manager: "G. Johnson",
        changeReason: "실제 비용"
      }
    ],
    equipmentHistory: [],
  },
  {
    id: uid(),
    pjtNo: "PJT-25109",
    name: "Houston Energy Management",
    country: "USA",
    city: "Houston",
    status: "진행 중(관리필요)",
    pm: "L. Davis",
    salesManagers: ["M. Wilson"],
    designManagers: ["N. Anderson"],
    controlManagers: ["O. Taylor"],
    productionManagers: ["P. Thomas"],
    progress: 75,
    startDate: "2025-02-01",
    endDate: "2025-10-31",
    lat: 29.7604,
    lng: -95.3698,
    address: "Houston, TX",
    note: "에너지 관리 시스템 - 비용 초과",
    budget: 38000000,
    actualCost: 36000000,
    costHistory: [
      {
        id: uid(),
        date: "2025-02-01",
        budget: 38000000,
        actualCost: 0,
        costRatio: 0.0,
        note: "프로젝트 시작",
        manager: "L. Davis",
        changeReason: "예산 설정"
      },
      {
        id: uid(),
        date: "2025-06-15",
        budget: 38000000,
        actualCost: 36000000,
        costRatio: 94.7,
        note: "비용 초과로 관리 필요",
        manager: "L. Davis",
        changeReason: "실제 비용 증가"
      }
    ],
    equipmentHistory: [],
  },
  {
    id: uid(),
    pjtNo: "PJT-25110",
    name: "Miami Digital Twin",
    country: "USA",
    city: "Miami",
    status: "진행 중",
    pm: "Q. Rodriguez",
    salesManagers: ["R. Martinez"],
    designManagers: ["S. Hernandez"],
    controlManagers: ["T. Lopez"],
    productionManagers: ["U. Gonzalez"],
    progress: 40,
    startDate: "2025-03-15",
    endDate: "2025-12-31",
    lat: 25.7617,
    lng: -80.1918,
    address: "Miami, FL",
    note: "디지털 트윈 시스템 구축",
    budget: 32000000,
    actualCost: 12800000,
    costHistory: [
      {
        id: uid(),
        date: "2025-03-15",
        budget: 32000000,
        actualCost: 0,
        costRatio: 0.0,
        note: "프로젝트 시작",
        manager: "Q. Rodriguez",
        changeReason: "예산 설정"
      },
      {
        id: uid(),
        date: "2025-06-20",
        budget: 32000000,
        actualCost: 12800000,
        costRatio: 40.0,
        note: "진행 중",
        manager: "Q. Rodriguez",
        changeReason: "실제 비용"
      }
    ],
    equipmentHistory: [],
  },
  {
    id: uid(),
    pjtNo: "PJT-25111",
    name: "Seattle Cloud Platform",
    country: "USA",
    city: "Seattle",
    status: "일시 중단",
    pm: "V. Brown",
    salesManagers: ["W. Davis"],
    designManagers: ["X. Wilson"],
    controlManagers: ["Y. Anderson"],
    productionManagers: ["Z. Taylor"],
    progress: 25,
    startDate: "2025-01-01",
    endDate: "2025-11-30",
    lat: 47.6062,
    lng: -122.3321,
    address: "Seattle, WA",
    note: "클라우드 플랫폼 일시 중단",
    budget: 28000000,
        actualCost: 7000000,
        costHistory: [
          {
            id: uid(),
            date: "2025-01-01",
            budget: 28000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "V. Brown",
            changeReason: "예산 설정"
          },
          {
            id: uid(),
            date: "2025-04-10",
            budget: 28000000,
            actualCost: 7000000,
            costRatio: 25.0,
            note: "일시 중단",
            manager: "V. Brown",
            changeReason: "실제 비용"
          }
        ],
        equipmentHistory: [],
      },
      {
        id: uid(),
        pjtNo: "PJT-25112",
        name: "Denver AI Integration",
        country: "USA",
        city: "Denver",
        status: "계획",
        pm: "A. Smith",
        salesManagers: ["B. Johnson"],
        designManagers: ["C. Williams"],
        controlManagers: ["D. Brown"],
        productionManagers: ["E. Jones"],
        progress: 0,
        startDate: "2025-09-01",
        endDate: "2026-02-28",
        lat: 39.7392,
        lng: -104.9903,
        address: "Denver, CO",
        note: "AI 통합 시스템",
        budget: 45000000,
        actualCost: 0,
        costHistory: [
          {
            id: uid(),
            date: "2025-09-01",
            budget: 45000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "A. Smith",
            changeReason: "예산 설정"
          }
        ],
        equipmentHistory: [],
      },
      {
        id: uid(),
        pjtNo: "PJT-25113",
        name: "Boston Smart Grid",
        country: "USA",
        city: "Boston",
        status: "진행 중",
        pm: "F. Garcia",
        salesManagers: ["G. Miller"],
        designManagers: ["H. Davis"],
        controlManagers: ["I. Wilson"],
        productionManagers: ["J. Anderson"],
        progress: 55,
        startDate: "2025-02-15",
        endDate: "2025-11-30",
        lat: 42.3601,
        lng: -71.0589,
        address: "Boston, MA",
        note: "스마트 그리드 시스템",
        budget: 52000000,
        actualCost: 28600000,
        costHistory: [
          {
            id: uid(),
            date: "2025-02-15",
            budget: 52000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "F. Garcia",
            changeReason: "예산 설정"
          },
          {
            id: uid(),
            date: "2025-06-25",
            budget: 52000000,
            actualCost: 28600000,
            costRatio: 55.0,
            note: "진행 중",
            manager: "F. Garcia",
            changeReason: "실제 비용"
          }
        ],
        equipmentHistory: [],
      },
      {
        id: uid(),
        pjtNo: "PJT-25114",
        name: "San Francisco Blockchain",
        country: "USA",
        city: "San Francisco",
        status: "완료",
        pm: "K. Taylor",
        salesManagers: ["L. Thomas"],
        designManagers: ["M. Rodriguez"],
        controlManagers: ["N. Martinez"],
        productionManagers: ["O. Hernandez"],
        progress: 100,
        startDate: "2024-10-01",
        endDate: "2025-03-31",
        lat: 37.7749,
        lng: -122.4194,
        address: "San Francisco, CA",
        note: "블록체인 시스템 완료",
        budget: 38000000,
        actualCost: 35500000,
        costHistory: [
          {
            id: uid(),
            date: "2024-10-01",
            budget: 38000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "K. Taylor",
            changeReason: "예산 설정"
          },
          {
            id: uid(),
            date: "2025-03-31",
            budget: 38000000,
            actualCost: 35500000,
            costRatio: 93.4,
            note: "프로젝트 완료",
            manager: "K. Taylor",
            changeReason: "실제 비용"
          }
        ],
        equipmentHistory: [],
      },
      // 유럽 프로젝트들 (총 5개)
      {
        id: uid(),
        pjtNo: "PJT-25201",
        name: "Berlin Industry 4.0",
        country: "Germany",
        city: "Berlin",
        status: "진행 중",
        pm: "H. Mueller",
        salesManagers: ["K. Schmidt"],
        designManagers: ["M. Weber"],
        controlManagers: ["P. Fischer"],
        productionManagers: ["R. Meyer"],
        progress: 65,
        startDate: "2025-01-01",
        endDate: "2025-10-31",
        lat: 52.5200,
        lng: 13.4050,
        address: "Berlin, Germany",
        note: "Industry 4.0 시스템 구축",
        budget: 55000000,
        actualCost: 35750000,
        costHistory: [
          {
            id: uid(),
            date: "2025-01-01",
            budget: 55000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "H. Mueller",
            changeReason: "예산 설정"
          },
          {
            id: uid(),
            date: "2025-06-15",
            budget: 55000000,
            actualCost: 35750000,
            costRatio: 65.0,
            note: "진행 중",
            manager: "H. Mueller",
            changeReason: "실제 비용"
          }
        ],
        equipmentHistory: [],
      },
      {
        id: uid(),
        pjtNo: "PJT-25202",
        name: "Paris Smart City",
        country: "France",
        city: "Paris",
        status: "계획",
        pm: "J. Dubois",
        salesManagers: ["L. Martin"],
        designManagers: ["A. Bernard"],
        controlManagers: ["P. Petit"],
        productionManagers: ["M. Moreau"],
        progress: 0,
        startDate: "2025-08-01",
        endDate: "2026-01-31",
        lat: 48.8566,
        lng: 2.3522,
        address: "Paris, France",
        note: "스마트 시티 인프라",
        budget: 42000000,
        actualCost: 0,
        costHistory: [
          {
            id: uid(),
            date: "2025-08-01",
            budget: 42000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "J. Dubois",
            changeReason: "예산 설정"
          }
        ],
        equipmentHistory: [],
      },
      {
        id: uid(),
        pjtNo: "PJT-25203",
        name: "London Digital Factory",
        country: "UK",
        city: "London",
        status: "진행 중(관리필요)",
        pm: "R. Wilson",
        salesManagers: ["S. Brown"],
        designManagers: ["T. Davis"],
        controlManagers: ["U. Johnson"],
        productionManagers: ["V. Smith"],
        progress: 85,
        startDate: "2025-02-01",
        endDate: "2025-09-30",
        lat: 51.5074,
        lng: -0.1278,
        address: "London, UK",
        note: "디지털 팩토리 - 비용 초과",
        budget: 48000000,
        actualCost: 45600000,
        costHistory: [
          {
            id: uid(),
            date: "2025-02-01",
            budget: 48000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "R. Wilson",
            changeReason: "예산 설정"
          },
          {
            id: uid(),
            date: "2025-06-20",
            budget: 48000000,
            actualCost: 45600000,
            costRatio: 95.0,
            note: "비용 초과로 관리 필요",
            manager: "R. Wilson",
            changeReason: "실제 비용 증가"
          }
        ],
        equipmentHistory: [],
      },
      {
        id: uid(),
        pjtNo: "PJT-25204",
        name: "Madrid IoT Network",
        country: "Spain",
        city: "Madrid",
        status: "일시 중단",
        pm: "C. Garcia",
        salesManagers: ["D. Rodriguez"],
        designManagers: ["E. Martinez"],
        controlManagers: ["F. Hernandez"],
        productionManagers: ["G. Lopez"],
        progress: 35,
        startDate: "2025-01-15",
        endDate: "2025-10-31",
        lat: 40.4168,
        lng: -3.7038,
        address: "Madrid, Spain",
        note: "IoT 네트워크 일시 중단",
        budget: 32000000,
        actualCost: 11200000,
        costHistory: [
          {
            id: uid(),
            date: "2025-01-15",
            budget: 32000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "C. Garcia",
            changeReason: "예산 설정"
          },
          {
            id: uid(),
            date: "2025-05-10",
            budget: 32000000,
            actualCost: 11200000,
            costRatio: 35.0,
            note: "일시 중단",
            manager: "C. Garcia",
            changeReason: "실제 비용"
          }
        ],
        equipmentHistory: [],
      },
      {
        id: uid(),
        pjtNo: "PJT-25205",
        name: "Rome Heritage Tech",
        country: "Italy",
        city: "Rome",
        status: "완료",
        pm: "M. Rossi",
        salesManagers: ["N. Bianchi"],
        designManagers: ["O. Romano"],
        controlManagers: ["P. Colombo"],
        productionManagers: ["Q. Marino"],
        progress: 100,
        startDate: "2024-11-01",
        endDate: "2025-04-30",
        lat: 41.9028,
        lng: 12.4964,
        address: "Rome, Italy",
        note: "문화유산 기술 시스템 완료",
        budget: 36000000,
        actualCost: 33800000,
        costHistory: [
          {
            id: uid(),
            date: "2024-11-01",
            budget: 36000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "M. Rossi",
            changeReason: "예산 설정"
          },
          {
            id: uid(),
            date: "2025-04-30",
            budget: 36000000,
            actualCost: 33800000,
            costRatio: 93.9,
            note: "프로젝트 완료",
            manager: "M. Rossi",
            changeReason: "실제 비용"
          }
        ],
        equipmentHistory: [],
      },
      // 중국 프로젝트들 (총 5개)
      {
        id: uid(),
        pjtNo: "PJT-25301",
        name: "Beijing AI Platform",
        country: "China",
        city: "Beijing",
        status: "진행 중",
        pm: "Li Wei",
        salesManagers: ["Zhang Ming"],
        designManagers: ["Wang Fang"],
        controlManagers: ["Chen Lei"],
        productionManagers: ["Liu Yang"],
        progress: 70,
        startDate: "2025-01-01",
        endDate: "2025-08-31",
        lat: 39.9042,
        lng: 116.4074,
        address: "Beijing, China",
        note: "AI 플랫폼 구축",
        budget: 45000000,
        actualCost: 31500000,
        costHistory: [
          {
            id: uid(),
            date: "2025-01-01",
            budget: 45000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "Li Wei",
            changeReason: "예산 설정"
          },
          {
            id: uid(),
            date: "2025-06-15",
            budget: 45000000,
            actualCost: 31500000,
            costRatio: 70.0,
            note: "진행 중",
            manager: "Li Wei",
            changeReason: "실제 비용"
          }
        ],
        equipmentHistory: [],
      },
      {
        id: uid(),
        pjtNo: "PJT-25302",
        name: "Shanghai Smart Port",
        country: "China",
        city: "Shanghai",
        status: "계획",
        pm: "Wu Jing",
        salesManagers: ["Zhou Bin"],
        designManagers: ["Xu Mei"],
        controlManagers: ["Sun Tao"],
        productionManagers: ["Guo Lin"],
        progress: 0,
        startDate: "2025-09-01",
        endDate: "2026-02-28",
        lat: 31.2304,
        lng: 121.4737,
        address: "Shanghai, China",
        note: "스마트 항구 시스템",
        budget: 52000000,
        actualCost: 0,
        costHistory: [
          {
            id: uid(),
            date: "2025-09-01",
            budget: 52000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "Wu Jing",
            changeReason: "예산 설정"
          }
        ],
        equipmentHistory: [],
      },
      {
        id: uid(),
        pjtNo: "PJT-25303",
        name: "Guangzhou Green Energy",
        country: "China",
        city: "Guangzhou",
        status: "진행 중(관리필요)",
        pm: "Huang Min",
        salesManagers: ["Luo Fei"],
        designManagers: ["Zeng Hong"],
        controlManagers: ["Peng Wei"],
        productionManagers: ["Jiang Bo"],
        progress: 90,
        startDate: "2025-02-01",
        endDate: "2025-07-31",
        lat: 23.1291,
        lng: 113.2644,
        address: "Guangzhou, China",
        note: "그린 에너지 시스템 - 비용 초과",
        budget: 38000000,
        actualCost: 37200000,
        costHistory: [
          {
            id: uid(),
            date: "2025-02-01",
            budget: 38000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "Huang Min",
            changeReason: "예산 설정"
          },
          {
            id: uid(),
            date: "2025-06-25",
            budget: 38000000,
            actualCost: 37200000,
            costRatio: 97.9,
            note: "비용 초과로 관리 필요",
            manager: "Huang Min",
            changeReason: "실제 비용 증가"
          }
        ],
        equipmentHistory: [],
      },
      {
        id: uid(),
        pjtNo: "PJT-25304",
        name: "Shenzhen Digital Twin",
        country: "China",
        city: "Shenzhen",
        status: "일시 중단",
        pm: "Yang Lei",
        salesManagers: ["Liu Mei"],
        designManagers: ["Chen Wei"],
        controlManagers: ["Wang Bin"],
        productionManagers: ["Zhang Tao"],
        progress: 45,
        startDate: "2025-01-15",
        endDate: "2025-10-31",
        lat: 22.3193,
        lng: 114.1694,
        address: "Shenzhen, China",
        note: "디지털 트윈 일시 중단",
        budget: 42000000,
        actualCost: 18900000,
        costHistory: [
          {
            id: uid(),
            date: "2025-01-15",
            budget: 42000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "Yang Lei",
            changeReason: "예산 설정"
          },
          {
            id: uid(),
            date: "2025-05-20",
            budget: 42000000,
            actualCost: 18900000,
            costRatio: 45.0,
            note: "일시 중단",
            manager: "Yang Lei",
            changeReason: "실제 비용"
          }
        ],
        equipmentHistory: [],
      },
      {
        id: uid(),
        pjtNo: "PJT-25305",
        name: "Chengdu Robotics",
        country: "China",
        city: "Chengdu",
        status: "완료",
        pm: "Zhao Min",
        salesManagers: ["Qian Wei"],
        designManagers: ["Sun Hong"],
        controlManagers: ["Wu Bin"],
        productionManagers: ["Li Tao"],
        progress: 100,
        startDate: "2024-12-01",
        endDate: "2025-05-31",
        lat: 30.5728,
        lng: 104.0668,
        address: "Chengdu, China",
        note: "로봇 시스템 완료",
        budget: 35000000,
        actualCost: 32500000,
        costHistory: [
          {
            id: uid(),
            date: "2024-12-01",
            budget: 35000000,
            actualCost: 0,
            costRatio: 0.0,
            note: "프로젝트 시작",
            manager: "Zhao Min",
            changeReason: "예산 설정"
          },
          {
            id: uid(),
            date: "2025-05-31",
            budget: 35000000,
            actualCost: 32500000,
            costRatio: 92.9,
            note: "프로젝트 완료",
            manager: "Zhao Min",
            changeReason: "실제 비용"
          }
        ],
        equipmentHistory: [],
      }
    ];
